[package]
name = "ssh-box"
version = "0.0.0"
authors = ["Tony Finch <dot@dotat.at>"]
edition = "2021"

[dependencies]
aes = { version = "~0", features = ["ctr"] }
anyhow = "~1"
base64 = "~0"
bcrypt-pbkdf = "~0"
getopts = "~0"
nom = "~7"
